// importing CSS
import './css/EnglishAlphabetWithPositionsCSS.css';

// main function
export function EnglishAlphabetWithPositions() {
    // HTML
    return (
        <div className="EnglishAlphabetWithPositions">
            <table className="EnglishAlphabetWithPositions__Table">
                <tr>
                    <td>A</td>
                    <td>1</td>
                </tr>
                <tr>
                    <td>B</td>
                    <td>2</td>
                </tr>
                <tr>
                    <td>C</td>
                    <td>3</td>
                </tr>
                <tr>
                    <td>D</td>
                    <td>4</td>
                </tr>
                <tr>
                    <td>E</td>
                    <td>5</td>
                </tr>
                <tr>
                    <td>F</td>
                    <td>6</td>
                </tr>
                <tr>
                    <td>G</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>H</td>
                    <td>8</td>
                </tr>
                <tr>
                    <td>I</td>
                    <td>9</td>
                </tr>
                <tr>
                    <td>J</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>K</td>
                    <td>11</td>
                </tr>
                <tr>
                    <td>L</td>
                    <td>12</td>
                </tr>
                <tr>
                    <td>M</td>
                    <td>13</td>
                </tr>
                <tr>
                    <td>N</td>
                    <td>14</td>
                </tr>
                <tr>
                    <td>O</td>
                    <td>15</td>
                </tr>
                <tr>
                    <td>P</td>
                    <td>16</td>
                </tr>
                <tr>
                    <td>Q</td>
                    <td>17</td>
                </tr>
                <tr>
                    <td>R</td>
                    <td>18</td>
                </tr>
                <tr>
                    <td>S</td>
                    <td>19</td>
                </tr>
                <tr>
                    <td>T</td>
                    <td>20</td>
                </tr>
                <tr>
                    <td>U</td>
                    <td>21</td>
                </tr>
                <tr>
                    <td>V</td>
                    <td>22</td>
                </tr>
                <tr>
                    <td>W</td>
                    <td>23</td>
                </tr>
                <tr>
                    <td>X</td>
                    <td>24</td>
                </tr>
                <tr>
                    <td>Y</td>
                    <td>25</td>
                </tr>
                <tr>
                    <td>Z</td>
                    <td>26</td>
                </tr>
            </table>
        </div>
    );
}